### ISSUE TITLE
Trouble stubbing YAML.load_file

### ISSUE THREAD

**Issue by faizaankhan** [rspec/rspec-metagem#37] opened 2019-04-10 13:32 UTC
Here's a snippet

The class where I'm loading YAML file
```
class FeatureStorageService
  FEATURES = YAML.load_file(Rails.root.join("config/features.yml"))
end
```
The test
```
describe FeatureStorageService do
  let!(:yaml)     { YAML.load_file(Rails.root.join("spec/factories/files/features.yml")) }

  before do
    allow(YAML).to receive(:load_file).and_call_original
    allow(YAML).to receive(:load_file).with(Rails.root.join("config/features.yml")).and_return(yaml)
  end
end
```

The spec doesn't load the file at "spec/factories/files/features.yml" instead loads the original one.
I have cross checked the syntax so many times.

Also, the stubbing works fine for my controller spec which is accessing the same service(class shown here) with the same syntax.

Dependencies:
  gem 'rspec-rails', '~> 3.4.2'
  gem 'rails', '4.2.7'

**Comment by JonRowe** [comment] 2019-04-10 13:40
Closing as wrong repo and duplicate of rspec/rspec-mocks#1272

**Closed as completed** 2019-04-10 13:40 UTC
